# Generated by Django 3.0.6 on 2020-05-27 19:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200528_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
